apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helmataart
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: helmataart.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helmataart
            port:
              number: 80
  - host: www.helmataart.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helmataart
            port:
              number: 80